name: BattleRoyale
main: com.plugin.ftb.battleroyale.BattleRoyale
version: 1.1.41
commands:
  battleroyale:
    usage:  /<command>
    permission: battleroyale.command
    
permissions:
  battleroyale.command:
    default: op